import { Inter } from "next/font/google";
import "./globals.css";
import TanstackProvider from "../../providers/TanstackProvider";
import Banner from "./components/banner/banner";
import Footer from "./components/Footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <div>
            <Banner />
            {children}
            <Footer />
          </div>
        </TanstackProvider>
      </body>
    </html>
  );
}

/*export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Banner/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}*/
