

export const products = [
    {
      id: 1,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6318.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: 'S/200',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 2,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6318.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 3,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6318.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 4,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6318.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
  ]

  export const laptos = [
    {
      id: 1,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6380.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 2,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6446.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 3,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6486.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 4,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6445.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
        id: 5,
        name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
        href: '#',
        imageSrc: 'https://www.oba-computer.com/fotos/6243.png',
        imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
        price: '',
        webPrice: 'S/ 165',
        stock: 1,
      },
  ]


  export const computadoras = [
    {
      id: 1,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/gydref/iasos/fff/ccc/compus/20240316095032.jpg',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 2,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/gydref/iasos/fff/ccc/compus/20240316095020.jpg',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 3,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/gydref/iasos/fff/ccc/compus/20240316094948.jpg',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 4,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/gydref/iasos/fff/ccc/compus/20240314144758.jpeg',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
  ]


  export const mouses = [
    {
      id: 1,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6418.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 2,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6354.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 3,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6305.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
    {
      id: 4,
      name: 'AUDIFONO GAMER, MSI, INMERSE GH30 V2 BLACK',
      href: '#',
      imageSrc: 'https://www.oba-computer.com/fotos/6306.png',
      imageAlt: "Front of TARJETA DE VIDEO, GCMS, RX 580 8GB.",
      price: '',
      webPrice: 'S/ 165',
      stock: 1,
    },
  ]